# Generated by Django 3.2.8 on 2021-10-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.JSONField(default=[], null=True, verbose_name='list of ncestor categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.FilePathField(allow_folders=True, blank=True, default='', max_length=200, null=True, path='category', verbose_name=''),
        ),
    ]
