# Generated by Django 3.2.8 on 2021-10-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211028_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.FilePathField(allow_folders=True, blank=True, default='', max_length=200, null=True, path=None, verbose_name=''),
        ),
    ]
