# Generated by Django 3.2.8 on 2021-10-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='paths',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
    ]
