# Generated by Django 3.2.8 on 2021-10-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211028_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.FilePathField(blank=True, max_length=200, null=True, path=None, verbose_name=''),
        ),
    ]
