# Generated by Django 3.2.8 on 2021-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='paths',
            field=models.JSONField(default=list, null=True, verbose_name=''),
        ),
    ]
