# Generated by Django 3.2.8 on 2021-10-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211028_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.FilePathField(blank=True, max_length=200, null=True, path='/', verbose_name=''),
        ),
    ]
