# Generated by Django 3.2.8 on 2021-10-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.FilePathField(allow_folders=True, blank=True, max_length=200, null=True, path='/', recursive=True, verbose_name=''),
        ),
    ]
