# Generated by Django 3.2.8 on 2021-10-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='paths',
            field=models.JSONField(default=list, null=True, verbose_name='list of ancestors'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='nested path to this category'),
        ),
    ]
