# Generated by Django 3.2.8 on 2021-10-30 16:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20211028_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='store.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='paths',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='list of ancestors'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Category slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='nested path to this category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alternative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='value',
            field=models.CharField(help_text='Product specification value (maximum of 250 words', max_length=250, verbose_name='value'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart', verbose_name='Cart ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Product Name')),
            ],
            options={
                'unique_together': {('product', 'cart')},
            },
        ),
    ]
